<?php
/**
 * Helper override for media uploader modifications.
 *
 * @category   Oye
 * @package    Oye_Themetuner
 * @author     OYE NETWORK LLC <oyenetwork@oyenetwork.com>
 */
class Oye_Themetuner_Helper_Wysiwyg_Images extends Mage_Cms_Helper_Wysiwyg_Images
{
    public function getImageMediaUrl($filename)
    {
        $fullPath = Mage::helper('cms/wysiwyg_images')->getCurrentPath();
        $imageUrl = $this->_getUrlSubdirPart() . rtrim(substr($fullPath, strpos($fullPath, '/media/')), '/') . DS . $filename;

        return $imageUrl;
    }
    
    /**
     * Detect if Magento was installed inside subdirectory and return
     * subdirectory part of the url. This is needed for setting background image paths correctly inside
     * css, generated by serverside code.
     *
     * @return string - subdirectory part of url, empty string if Magento was not installed into subdirectory
     */
    private function _getUrlSubdirPart() {
        $possibleSubdir =  str_replace($_SERVER['DOCUMENT_ROOT'], '', $_SERVER["SCRIPT_FILENAME"]);
        
        $onlyDirs = array();
        if (strpos($_SERVER['REQUEST_URI'], $possibleSubdir) === 0) {
            // request uri has subdirectory
            $dirs = explode(DS, $possibleSubdir);
            
            // remove filename part
            $onlyDirs = array();
            foreach ($dirs as $dir) {
                if (strpos($dir, '.') === false) {
                    $onlyDirs[] = $dir;
                }
            }
        }
        return implode(DS, $onlyDirs);
    }
}